apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: proxy
  namespace: {{ .namespace }}

spec:
  hosts:
  - proxy
  http:
  - route:
    - destination:
        host: proxy
      weight: 100
